#!/bin/sh

# $FreeBSD: vulture_shellinabox startup script 13-08-2019 $
#
# Shell in a Box Daemon startup script
#
# PROVIDE: vulture_shellinaboxd
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following to /etc/rc.conf[.local] to enable this service
#
# vulture_shellinaboxd_enable="YES"
#
# You can fine tune others variables too:
# vulture_shellinaboxd_pidfile="/var/run/shellinabox.pid"
# vulture_shellinaboxd_user="shellinabox"
# vulture_shellinaboxd_group="shellinabox"
# vulture_shellinaboxd_port="4200"
# vulture_shellinaboxd_certdir="/usr/local/etc/shellinabox"
# vulture_shellinaboxd_certfile=
#       Example: vulture_shellinaboxd_certfile="/your/cert.pem"
# vulture_shellinaboxd_flags=

vulture_shellinaboxd_precmd() {
        if command -v check_namevarlist > /dev/null 2>&1; then
                check_namevarlist fib && return 0
        fi

        ${SYSCTL} net.fibs >/dev/null 2>&1 || return 0

        vulture_shellinaboxd_fib=${vulture_shellinaboxd_fib:-"NONE"}
        case "$vulture_shellinaboxd_fib" in
        [Nn][Oo][Nn][Ee])
                ;;
        *)
                command="setfib -F ${vulture_shellinaboxd_fib} ${command}"
                ;;
        esac
}

. /etc/rc.subr

name="vulture_shellinaboxd"
rcvar=vulture_shellinaboxd_enable

command="/usr/local/bin/shellinaboxd"
start_precmd="vulture_shellinaboxd_precmd"

load_rc_config $name

vulture_shellinaboxd_enable=${vulture_shellinaboxd_enable:-"NO"}
vulture_shellinaboxd_user=${vulture_shellinaboxd_user:-"shellinabox"}
vulture_shellinaboxd_group=${vulture_shellinaboxd_group:-"shellinabox"}
vulture_shellinaboxd_port=${vulture_shellinaboxd_port:-"4200"}
vulture_shellinaboxd_certdir=${vulture_shellinaboxd_certdir:-"/usr/local/etc/shellinabox"}

pidfile=${vulture_shellinaboxd_pidfile:-"/var/run/shellinaboxd.pid"}

command_args="--user=${vulture_shellinaboxd_user} --group=${vulture_shellinaboxd_group} --localhost-only -t --port=${vulture_shellinaboxd_port} --background=${pidfile}"

# avoid unnecessary su(1) initiated by rc.subr
unset vulture_shellinaboxd_user vulture_shellinaboxd_group

run_rc_command "$1"
