#!/bin/sh
#
#

# PROVIDE: vultured
# REQUIRE: jail
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `vultured':
#
# vultured_enable="YES"
#

. /etc/rc.subr

name="vultured"
rcvar=vultured_enable

load_rc_config $name

: ${vultured_enable="NO"}

vultured_user="vlt-os"
pidfile="/var/run/vulture/vultured.pid"
procname="/home/vlt-os/env/bin/python3.7"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} ${procname} /home/vlt-os/vulture_os/daemons/cluster.py"

# Redefine status function to use only pid file (solve issue with old python)
status_cmd="${name}_status"
vultured_status() {
    if [ -f $pidfile ] ; then
        echo "$name is running as pid $(/bin/cat $pidfile)".
    else
        echo "$name is not running."
    fi
}

run_rc_command "$1"
