#!/bin/sh

# $FreeBSD: vulture shellinabox startup script 13-08-2019 $
#
# Shell in a Box Daemon startup script
#
# PROVIDE: shellinaboxd
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following to /etc/rc.conf[.local] to enable this service
#
# shellinaboxd_enable="YES"
#
# You can fine tune others variables too:
# shellinaboxd_pidfile="/var/run/shellinabox.pid"
# shellinaboxd_user="shellinabox"
# shellinaboxd_group="shellinabox"
# shellinaboxd_port="4200"
# shellinaboxd_certdir="/usr/local/etc/shellinabox"
# shellinaboxd_certfile=
#       Example: shellinaboxd_certfile="/your/cert.pem"
# shellinaboxd_flags=

shellinaboxd_precmd() {
        if command -v check_namevarlist > /dev/null 2>&1; then
                check_namevarlist fib && return 0
        fi

        ${SYSCTL} net.fibs >/dev/null 2>&1 || return 0

        shellinaboxd_fib=${shellinaboxd_fib:-"NONE"}
        case "$shellinaboxd_fib" in
        [Nn][Oo][Nn][Ee])
                ;;
        *)
                command="setfib -F ${shellinaboxd_fib} ${command}"
                ;;
        esac
}

. /etc/rc.subr

name="shellinaboxd"
rcvar=shellinaboxd_enable

command="/usr/local/bin/${name}"
start_precmd="shellinaboxd_precmd"

load_rc_config $name

shellinaboxd_enable=${shellinaboxd_enable:-"NO"}
shellinaboxd_user=${shellinaboxd_user:-"shellinabox"}
shellinaboxd_group=${shellinaboxd_group:-"shellinabox"}
shellinaboxd_port=${shellinaboxd_port:-"4200"}
shellinaboxd_certdir=${shellinaboxd_certdir:-"/usr/local/etc/shellinabox"}

pidfile=${shellinaboxd_pidfile:-"/var/run/shellinaboxd.pid"}

command_args="--user=${shellinaboxd_user} --group=${shellinaboxd_group} --localhost-only -t --port=${shellinaboxd_port} --background=${pidfile}"

# avoid unnecessary su(1) initiated by rc.subr
unset shellinaboxd_user shellinaboxd_group

run_rc_command "$1"