#!/bin/csh

set allowed=1
foreach arg ($*)
    if ( "$arg" == "upgrade" ) then
        set allowed=0
    endif
end

if ( $allowed ) then
    /usr/sbin/pkg $*
else
    cat - << EOF
[1m[38;5;196m    *** Administration restriction ***
[1m[38;5;196m    Don't use this command until you know what you're doing
[0m[1m To upgrade you're Vulture, please instead use the following commands :
[1m[38;5;33m o update_system          (/home/vlt-adm/system/update_system.sh)
[1m[38;5;33m o update_system_lite     (/home/vlt-adm/system/update_system_lite.sh)
[0m

EOF
endif
